apiVersion: apps/v1
kind: Deployment
metadata:
  name: ota-adapters
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ota-adapter
  template:
    metadata:
      labels:
        app: ota-adapter
    spec:
      containers:
      - name: ota-adap-container
        image:  172.27.56.53:5000/adapterimage
        imagePullPolicy: Always
        ports:
        - containerPort: 9000