[package]
name = "supplier"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "*"
actix-web = "4.7.0"
rand ="0.8.5"
async-std = "1.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[[bin]]
name = "supplier"



